import localFont from "next/font/local";
import React, { ReactNode } from "react";
import "./globals.css";
import Header from "@/components/layout/Navigation";
import { Metadata } from "next";
import { CartProvider } from '@/utils/cartcontext'; 
import Footer from "@/components/layout/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Audu Techinal Test",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <CartProvider>
          <Header />
          {children}
          <Footer/>
        </CartProvider>
      </body>
    </html>
  );
}
